<?php
    // Consider to use SQL
    $tips = array("Ctrl A means select all and Ctrl C copy them",
             "Ctrl Z undo last step, Ctrl Y redo it",
             "Ctrl T will open a blank tab in brower",
             "Ctrl N will open a new window",
             "When you don't know what to do, press F1",
             "It's weird that Mac's Ctrl is not Ctrl but Command",
             "Ctrl W close current tab",
             "Alt F4 close current window",
             "Do you know the most deadly weapon in Linux? sudo rm -rf /",
             "During starting up, press F2 or Del before Windows icon appears will allow you enter UEFI, magical world",
             "It's a bit to come out these tips!",
             "What is Ctrl C in Bash? Shift Insert!",
             "Git is perfect and everyone should have one",
             "As well as Github",
             "Or Gitlab",
             "PHP is the best programming language!",
             "No, the best programming language is Python!",
             "Have you heard of rubies carried by trains on rails?",
             "Want some coffee?",
             "<a href=\"https://c9.io\">Cloud 9, perfect place to start your web development</a>",
             "I am confused, which callback I am in?",
             "NodeJs: where is my friends?",
             "Every version of Android has surprise!",
             "Siri or Cortana?",
             "Have you heard of jokes that are about programmers and PR? Go Google it!",
             "I think I will use MySQL for these tips",
             "Why TheToolBox got its name? Because ToolBox.online was expensive!",
             "Every Ad click you make is supporting my development on this website, thank you!",
             "If you have trouble loading this page, please press F12 and copy the error message in the console section and email me, thanks for your feedback!",
             "You can always email me if you can!",
             "Share you idea of improvement on the git repository of this site on <a href=\"https://github.com/William-An/Tool-Website\">Github</a>"
             );
             echo $tips[array_rand($tips,1)];
?>
